apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}--env
data:

  AWS_ACCESS_KEY_ID: "${PROXY_KIBANA_AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${PROXY_KIBANA_AWS_SECRET_ACCESS_KEY}"
  AWS_DEFAULT_REGION: "${PROXY_KIBANA_AWS_DEFAULT_REGION}"
  GOLANG_DOWNLOAD_URL: "$(GOLANG_DOWNLOAD_URL)"

  TARGET_URL: "$(TARGET_URL)"
  LOGIN_USER: "$(LOGIN_USER)"
  LOGIN_HASHED_PASSWORD: "$(LOGIN_HASHED_PASSWORD)"

---
kind: Service
apiVersion: v1
metadata:
  name: ${APP_NAME}--pod
  labels:
    app: ${APP_NAME}
spec:
  selector:
    name: ${APP_NAME}--proxy-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${APP_NAME}--pod
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ${APP_NAME}--proxy-pod
  template:
    metadata:
      labels:
        name: ${APP_NAME}--proxy-pod
    spec:
      nodeSelector:
        nodegroup: ${PROXY_NODE_GROUP}
      restartPolicy: Always
      containers:
      - name: ${APP_NAME}--proxy-container
        image: ${IMAGE_NAME}
        command: ["go-wrapper", "run"]
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        envFrom:
          - configMapRef:
              name: ${APP_NAME}--env
